application:
  security:
    secret: ${SECRET}
    secure_cookies: ${SECURE_COOKIES:true}
    expiration_sec:
      access_token: ${ACCESS_TOKEN_EXPIRATION_SEC:1800}
      refresh_token: ${REFRESH_TOKEN_EXPIRATION_SEC:172800}
  external:
    viacep:
      url: ${CEP_SERVICE_URL:https://viacep.com.br/ws/%s/json/}
      timeout_in_millis: ${CEP_SERVICE_TIMEOUT:5000}
  name: ${BANK_NAME:BancoBR}
  timezone:
    zone_id: ${TIMEZONE:America/Sao_Paulo}

spring:
  application:
    name: BancoDigitalP2
  profiles:
    active: pgdev

server:
  port: ${BD_PORT:9999}
  error:
    include-stacktrace: never