logging:
  level:
    com:
      prpa: ${LOG_APPLICATION:DEBUG}
    org:
      hibernate: ${LOG_HIBERNATE:INFO}
      springframework:
        root: ${LOG_ROOT:INFO}
        web: ${LOG_WEB:INFO}
        security: ${LOG_SEC:INFO}
        transaction:
          interceptor: ${LOG_TRANSACTION:INFO}
        orm:
          jpa: ${LOG_JPA:INFO}

application:
  security:
    secret: ${SECRET:123}
    secure_cookies: false
  aop:
    logging: true
  repository:
    query:
      path: /sql/queries

spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_SCHEMA:dev}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always
      data-locations: classpath*:sql/data/politica_uso.sql,classpath*:sql/data/tier.sql,classpath*:sql/data/**
      schema-locations: classpath*:sql/schemas/politica_uso.sql,classpath*:sql/schemas/tier.sql,classpath*:sql/schemas/endereco.sql,classpath*:sql/schemas/**

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html